name = "MekaCR"
author = "TheMade4"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb89f59183ee31319c772f089dde497c8b87be18d6cee2c7ce3f4f5edd9a3a12"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
