name = "MekaCR"
author = "TheMade4"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "950d440a1dd2705cbc23746cf0f749ef895cf4a1b6acdecc51cd0676da413a7b"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
