name = "MekaCR"
author = "TheMade4"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4b54b5b7afcf0814c270b34e2d7132fed238ca7ffc8580ae521daa654c7db2d"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
