name = "MekaCR"
author = "TheMade4"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86f47306a51a3f31977d7fe30ed0284caed00241f4a40217de8ac73ea36cd09d"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
